Pull request №1
Lobachev27/ubereats-demo-frontend pull request #1
Opened 2018-04-12 17:25 UTC by Lobachev27

67/5000
Adaptive layout of two pages of the website UberEats was completed

2018-04-22 21:04 UTC, evgenyrodionov commented
Жипег какой-то

![image](https://user-images.githubusercontent.com/775692/39099862-e3bfd1f8-4689-11e8-91eb-1630e8364fb6.png)

2018-04-22 21:13 UTC, imevro requested changes
в целом хорошо, по мотивам написал частые ошибки в первом этапе курса (появится утром в понедельник)

https://erodionov.ru/courses/verstka/FhTKluFzm7

2018-04-22 21:13 UTC, evgenyrodionov commented on test/index.html
> +<!DOCTYPE html>
я думаю к ubereats это не очень относится)

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/css/normalize.css
> +/*! normalize.css v8.0.0 | MIT License | github.com/necolas/normalize.css */
написал об этом в частых ошибках — используй нормалайз через сдн или поставь ярном

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/index.html
> +  <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
точно нужны все начертания?

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/index.html
> +        <div class="col-xs-5 col-md-2 col-lg-2">
сетка в хедере не особо нужна

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/index.html
> +            <img class="logo__item" src="./img/logo-black.svg" alt="UberEats" title="UberEats">
прочитай в частых ошибках про итем-хуитем

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/index.html
> +          <div class="col-xs-12">
а зачем тут колонки? вытащи в контейнер

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/page_two.html
> +<!DOCTYPE html>
слабый нейминг файла

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/page_two.html
> +              <h2 class="tavern__info">₽₽₽ • Европейская</h2>
это разве заголовок? это же просто описание

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/page_two.html
> +  <link rel="stylesheet" href="./css/styles.css">
раздели стили

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/page_two.html
> +          <div class="col-xs-12">
опять же, вытащи в контейнер, не плоди вложенность сетки

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/css/styles.css
> +  height: 72px;
нет, фиксированный размер задаётся только картинкам

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/css/styles.css
> +  align-items: center;
а зачем флексы для изображения?

2018-04-22 21:13 UTC, evgenyrodionov commented on ubereats/css/styles.css
> +  height: 40px;
опять же

2018-04-26 19:21 UTC, Lobachev27 commented
All comments on the project were corrected

2018-05-02 21:33 UTC, imevro requested changes
так и не понял почему ты не вытащил из директории `ubereats` основной проект

всё остальное вроде норм

2018-05-02 21:33 UTC, evgenyrodionov commented on ubereats/page_two.html
> +              <h2 class="tavern__info">₽₽₽ • Европейская</h2>
и?

2018-05-12 08:54 UTC, Lobachev27 commented
Вытащил основной проект из директории ubereats

2018-06-03 20:26 UTC, merged

2018-06-03 20:26 UTC, evgenyrodionov commented
Если будешь делать новые бранчи — сначала сделай в мастере гит пулл